#!/bin/sh

# 引数としてコミットメッセージテンプレートファイルのパスが渡ってくる
commit_msg_template=$1

# 現在のブランチ名を取得
current_branch=$(git rev-parse --abbrev-ref HEAD)

# ブランチ名に "/" が入ると、sedの検索パターンの区切り文字と衝突する
# なので、パターンの区切り文字を "@" に変更
sed -i "s@\[Branch\]@$current_branch@" $commit_msg_template