/**
 * 【Next.jsキャッチアップ】【Frontend】【AppEntry】【ルートレイアウト】【概要】アプリ全体に共通するHTML骨格(html/body)を定義するルートレイアウト
 * 【Next.jsキャッチアップ】【Frontend】【AppEntry】【ルートレイアウト】【概要】フォント(Geist)の読み込み、faviconの設定、グローバルCSSの適用をここで一括管理する
 * 【Next.jsキャッチアップ】【Frontend】【AppEntry】【ルートレイアウト】【概要】各ページのコンテンツはchildrenとしてbody内に差し込まれる
 *
 * 【Next.jsキャッチアップ】【Frontend】【AppEntry】【ルートレイアウト】【関連】src/styles/globals.css : グローバルCSS(Tailwindの初期化とCSS変数の定義)
 * 【Next.jsキャッチアップ】【Frontend】【AppEntry】【ルートレイアウト】【関連】public/favicon.ico     : ブラウザタブに表示するアイコン
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // favicon.ico を public/ に置いているため、app/ 規約の自動認識が効かず明示指定が必要
  // 変更が反映されない場合はサーバー再起動 + Ctrl+Shift+R（強制リロード）が必要（ブラウザがファビコンを強くキャッシュするため）
  icons: {
    icon: "/favicon.ico",
  },
};

/**
 * 全ページを包む共通レイアウトコンポーネント
 *
 * @param children - アクセスしたURLに対応するページのコンテンツ
 *                   Next.jsのルーティングが自動的にここへ渡す
 *
 * @remarks
 * App RouterではすべてのルートがこのRootLayoutの子として描画される
 * たとえば/blogにアクセスするとblog/page.tsxの内容がchildrenとしてbody内に入る
 * ページをまたいで共通表示したいヘッダーやフッターがあればここに追加する
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      // 拡張機能で付与されるHTMLがhydration warningを出すので、抑制する
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
